### ISSUE TITLE
!render doesn't detect hidden mod

### ISSUE THREAD

**Issue by shrublet** [LeaPhant/flowabot#50]
I saw that hidden was implemented a while back (yay!), but it isn't rendered if it's included in the mod arguments (e.g. !render +hddt). It only renders if no + precedes 'hd' which seems a bit odd. This means that rendering directly from a score that uses hidden means flowabot doesn't render with hd. Hope this can be fixed! Thanks again for your hard work :)

**Comment by LeaPhant** [comment]
Although I agree it's confusing it's actually on purpose so you can choose for yourself whether you wanna see the play with HD or not, since for many people it's just preference. The people I asked wanted it that way (including myself). I'll find a better solution in the future (per user settings could be cool).
